// src/components/auth/signin.jsx
import React, { Component } from 'react';
import { reduxForm, Field } from 'redux-form';
import { getLoginStatus } from '../../actions/actions.js';
import { bindActionCreators } from 'redux';
import {connect} from 'react-redux';


class Signin extends Component {
    constructor(props) {
        super(props);
        this.handleFormSubmit = this.handleFormSubmit.bind(this);
    }
    handleFormSubmit(email, password) {
        this.props.getLoginStatus();
    }
    render() {
        const { handleSubmit } = this.props;
        return (
            <form onSubmit={handleSubmit(this.handleFormSubmit)}>
                <fieldset className="form-group">
                    <label>Email:</label>
                    <Field className="form-control" name="email" component="input" type="text" placeholder="email" />
                </fieldset>
                <fieldset className="form-group">
                    <label>password:</label>
                    <Field className="form-control" name="password" component="input" type="text" placeholder="password" />
                </fieldset>
                <button action="submit" className="btn btn-primary">Sign In</button>
            </form>
        );
    }
}
function mapDispatchToProps(dispatch) {
    return bindActionCreators({getLoginStatus}, dispatch)
}
 Signin = reduxForm({
    form: 'signin'
})(Signin);

Signin = connect(null,mapDispatchToProps)(Signin)

export default Signin;

// src/components/auth/signin.vue
<template>
  <form v-on:submit.prevent="onSubmit">
    <fieldset class=" form-group ">
      <label>Email:</label>
      <input class="form-control " name="email " type="text " placeholder="email" v-model="email" />
    </fieldset>
    <fieldset class="form-group ">
      <label>password:</label>
      <input class="form-control " name="password " type="text " placeholder="password" v-model="password" />
    </fieldset>
    <button action="submit " class="btn btn-primary ">Sign In</button>
  </form>
</template>

<script>
import { mapActions } from 'vuex'

export default {
  data() {
    return {
      email: null,
      password: null
    }
  },
  methods: {
    ...mapActions(['getLoginStatus']),
    onSubmit() {
      this.getLoginStatus({
        email: this.email,
        password: this.password
      })
    }
  }
}
</script>
